intf_libs = # Interface dependencies.
impl_libs = # Implementation dependencies.

pub = [dir_path] ../include/cglm/

include $pub

pub_hdrs = $($pub/ pub_hdrs)

lib{cglm}: {c}{**} $pub/{$pub_hdrs} $impl_libs $intf_libs

# Build options.
#
out_pfx_inc = [dir_path] $out_root/include/
src_pfx_inc = [dir_path] $src_root/include/
out_pfx_src = [dir_path] $out_root/cglm/
src_pfx_src = [dir_path] $src_root/cglm/

c.poptions =+ "-I$out_pfx_src" "-I$src_pfx_src" \
              "-I$out_pfx_inc" "-I$src_pfx_inc"
c.libs += -lm

{hbmia obja}{*}: c.poptions += -DCGLM_STATIC_BUILD
{hbmis objs}{*}: c.poptions += -DCGLM_SHARED_BUILD
if ($c.target.class == 'windows')
	objs{*}: c.poptions += -DCGLM_EXPORTS

# Export options.
#
lib{cglm}:
{
  c.export.poptions = "-I$out_pfx_inc" "-I$src_pfx_inc"
  c.export.libs = $intf_libs
}

liba{cglm}: c.export.poptions += -DCGLM_STATIC
libs{cglm}: c.export.poptions += -DCGLM_SHARED


# For pre-releases use the complete version to make sure they cannot be used
# in place of another pre-release or the final version. See the version module
# for details on the version.* variable values.
#
if $version.pre_release
  lib{cglm}: bin.lib.version = "-$version.project_id"
else
  lib{cglm}: bin.lib.version = "-$version.major.$version.minor"

# Don't install private headers.
#
h{*}: install = false
